In [1]:
import numpy as np
import matplotlib.pyplot as plt
import napari

In [51]:
original = np.fromfile('lung424_400x400x400.raw', dtype=np.uint8)
original = original.reshape((400, 400, 400))
original = original.astype(np.uint16)
l_min = np.fromfile('automate_400x400_rays/lung424_400x400x400.raw_400x400x400_20_min.raw', dtype=np.uint16)
l_min = l_min.reshape((400, 400, 400))

original = original == 0

l_min = l_min[:100]
original = original[:100]

In [61]:
# watershed
from skimage.segmentation import watershed
from skimage.feature import peak_local_max
from scipy import ndimage

l_slice = l_min[0]
coords = peak_local_max(l_min, min_distance=20, threshold_abs=l_min.mean() + 1.5*l_min.std())

#coords = peak_local_max(l_min, min_distance=5, threshold_abs=0.1)
print(coords)
mask = np.zeros(original.shape, dtype=bool)
mask[tuple(coords.T)] = True
markers, _ = ndimage.label(mask)

labels = watershed(-l_min, markers=markers, mask=original)

[[ 21 239 217]
 [ 48 269 142]
 [ 29 115  68]
 [ 20 113 344]
 [ 66 119  32]
 [ 67  25 211]]


In [62]:
# visualize results
viewer = napari.Viewer()
viewer.add_image(original, name='original')
viewer.add_image(labels, name='labels')

<Image layer 'labels' at 0x484403140>

In [59]:
markers

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [33]:
napari.imshow(markers)

(Viewer(camera=Camera(center=(0.0, np.float64(199.5), np.float64(199.5)), zoom=np.float64(3.417966360856269), angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(np.float64(0.0), 1.0, 0.0), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=3, ndisplay=2, order=(0, 1, 2), axis_labels=('0', '1', '2'), rollable=(True, True, True), range=(RangeTuple(start=np.float64(0.0), stop=np.float64(1.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(399.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(399.0), step=np.float64(1.0))), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(np.float64(0.0), np.float64(199.0), np.float64(199.0)), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'markers' at 0x46fddf2f0>], help='use <2> for transform', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='dark'